[package]
name = "mos6510_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.58", features = ["full"] }
proc-macro2 = "1.0.79"
once_cell = "1.19.0"

[lib]
proc-macro = true
path = "src/lib.rs"
